### ISSUE TITLE
Specially marked menu entries with X-Red-Hat categories

### ISSUE THREAD

**Issue by rapgro** [lxde/libqtxdg#67]
Custom category marks get ignored. For instance, Yumex and Yumex-DNF are expected to be grouped into Administration menu but they show in Settings menu.
Downstream: https://bugzilla.redhat.com/show_bug.cgi?id=1217565

Here's a sample:
```
$ cat /usr/share/applications/yumex-dnf.desktop 
[Desktop Entry]
Name=Yum Extender (DNF)
Comment=Install, update and remove applications
Categories=System;Settings;X-Red-Hat-Base;X-Fedora;
Icon=yumex-dnf
Exec=/usr/bin/yumex-dnf
Type=Application
Terminal=false
Encoding=UTF-8
GenericName=Software Installer

$ grep Red-Hat /etc/xdg/menus/* 2>/dev/null
/etc/xdg/menus/applications.menu:        <Not><Category>X-Red-Hat-ServerConfig</Category></Not>
/etc/xdg/menus/documentation.menu:      <Category>X-Red-Hat-Base</Category>
/etc/xdg/menus/server-settings.menu:      <Category>X-Red-Hat-Base</Category>
/etc/xdg/menus/server-settings.menu:      <Category>X-Red-Hat-ServerConfig</Category>
/etc/xdg/menus/server-settings.menu:        <Not><Category>X-Red-Hat-Base-Only</Category></Not>
/etc/xdg/menus/server-settings.menu:        <Not><Category>X-Red-Hat-Base</Category></Not>
/etc/xdg/menus/server-settings.menu:        <Category>X-Red-Hat-ServerConfig</Category>
/etc/xdg/menus/system-settings.menu:      <Not><Category>X-Red-Hat-ServerConfig</Category></Not>
```

**Comment by pmattern** [comment]
This issue has nothing to do with libqtxdg or any custom value `X-*` of key Categories in desktop entry files. Rather, it's due to custom Fedora files `*.menu` which are handling values `Settings` and `System` of key Categories differently than their upstream counterparts.

E. g. compare `kf5-applications.menu` that's used by default in KDE Plasma 5 with it's upstream counterpart applications.menu from KService (see https://projects.kde.org/projects/frameworks/kservice/repository):
Menu "System" excludes desktop entry files stating value `Settings` in key Categories as well
```
<Menu>
    <Name>System</Name>
    <Directory>kf5-system.directory</Directory>
    <Include>
        <And>
            <Category>System</Category>
            <Not><Category>Settings</Category></Not>     *
```
Same thing the other way around with menu "Settings"
```
<Menu>
    <Name>Settingsmenu</Name>
    <Directory>kf5-settingsmenu.directory</Directory>
    <Include>
        <And>
            <Category>Settings</Category>
            <Not><Category>System</Category></Not>       *
```
And an additional menu "Administration" is introduced picking up all desktop entry files stating both `Settings` and `System` in key Categories
```
<Menu>
    <Name>System Settings</Name>
    <Directory>SystemConfig.directory</Directory>
    <Include>
        <And>
            <Category>System</Category>                        *
            <Category>Settings</Category>                      *
```
None of these three features exists upstream. Same thing with `xfce-applications.menu` from Xfce's garcon (see http://git.xfce.org/xfce/garcon/).

`lxqt-applications.menu` used by LXQt excludes desktop entry files from menu "System" in a similar way as stated above only.
This is why desktop entry files stating both `Settings` and `System` end up in menu "Settings".

Of course it could be discussed to change lxqt-applications.menu upstream. But IMO the current behaviour makes sense. 
Dropping value `Settings` from key Categories as proposed by the patch in https://bugzilla.redhat.com/show_bug.cgi?id=1217565 would make the corresponding applications appear in menu "System" which is quite different than the current behaviour in KDE and Xfce on Fedora.
But if you want the placement of Yumex to be consistent with other desktop environments you have to tweak lxqt-applications.menu accordingly. Again, the discrepancy is not LXQt vs. other desktop environments but Fedoras custom *.menu files vs. those provided by all kinds of desktop environments upstream.

**Comment by kkofler** [comment]
This is indeed a downstream Fedora issue: The LXQt packaging needs something like this:
http://pkgs.fedoraproject.org/cgit/kf5-kservice.git/commit/?id=6f662a1e28d864e71ed8b4f1c5b1e126c191e57f
with Requires: redhat-menus for translations of the added categories:
http://pkgs.fedoraproject.org/cgit/kf5-kservice.git/commit/?id=2943978001307e47f2df873a893977b372ec0bc6

**Comment by pmattern** [comment]
Alright then.
